# Generated by Django 5.0.14 on 2026-01-08 13:17

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0002_add_is_active_to_base_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Системный код')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_purchased', models.BooleanField(default=False, verbose_name='Закупаемая позиция')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Вид справочника',
                'verbose_name_plural': 'Виды справочников',
                'db_table': 'catalog_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('mobile_phone', models.CharField(blank=True, max_length=50, verbose_name='Мобильный телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основное контактное лицо')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Контактное лицо',
                'verbose_name_plural': 'Контактные лица',
                'db_table': 'contact_persons',
                'ordering': ['-is_primary', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCatalogCategory',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, verbose_name='Системный код')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_purchased', models.BooleanField(default=False, verbose_name='Закупаемая позиция')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Вид справочника',
                'verbose_name_plural': 'historical Виды справочников',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalContactPerson',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('mobile_phone', models.CharField(blank=True, max_length=50, verbose_name='Мобильный телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основное контактное лицо')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Контактное лицо',
                'verbose_name_plural': 'historical Контактные лица',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalNomenclatureSupplier',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('delivery_days', models.PositiveIntegerField(default=7, verbose_name='Срок поставки (дней)')),
                ('supplier_article', models.CharField(blank=True, max_length=100, verbose_name='Артикул поставщика')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Цена')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('min_order_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Мин. кол-во заказа')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Приоритетный поставщик')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Поставщик номенклатуры',
                'verbose_name_plural': 'historical Поставщики номенклатуры',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='NomenclatureSupplier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_days', models.PositiveIntegerField(default=7, verbose_name='Срок поставки (дней)')),
                ('supplier_article', models.CharField(blank=True, max_length=100, verbose_name='Артикул поставщика')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Цена')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('min_order_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Мин. кол-во заказа')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Приоритетный поставщик')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Поставщик номенклатуры',
                'verbose_name_plural': 'Поставщики номенклатуры',
                'db_table': 'nomenclature_suppliers',
                'ordering': ['-is_primary', 'delivery_days'],
            },
        ),
        migrations.RemoveField(
            model_name='historicalsupplieroffer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalsupplieroffer',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='historicalsupplieroffer',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalsupplieroffer',
            name='nomenclature_item',
        ),
        migrations.RemoveField(
            model_name='historicalsupplieroffer',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='historicalsupplieroffer',
            name='updated_by',
        ),
        migrations.AlterUniqueTogether(
            name='supplieroffer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='supplieroffer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='supplieroffer',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='supplieroffer',
            name='nomenclature_item',
        ),
        migrations.RemoveField(
            model_name='supplieroffer',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='supplieroffer',
            name='updated_by',
        ),
        migrations.AlterModelOptions(
            name='historicalnomenclatureitem',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Номенклатурная позиция', 'verbose_name_plural': 'historical Номенклатурные позиции'},
        ),
        migrations.AlterModelOptions(
            name='nomenclatureitem',
            options={'ordering': ['catalog_category__sort_order', 'code'], 'verbose_name': 'Номенклатурная позиция', 'verbose_name_plural': 'Номенклатурные позиции'},
        ),
        migrations.AlterModelOptions(
            name='nomenclaturetype',
            options={'ordering': ['catalog_category__sort_order', 'name'], 'verbose_name': 'Тип номенклатуры', 'verbose_name_plural': 'Типы номенклатуры'},
        ),
        migrations.RemoveIndex(
            model_name='nomenclatureitem',
            name='nomenclatur_categor_301008_idx',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='historicalcontractor',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='historicalnomenclatureitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='historicalnomenclatureitem',
            name='default_supplier',
        ),
        migrations.RemoveField(
            model_name='historicalnomenclatureitem',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='historicalnomenclaturetype',
            name='category',
        ),
        migrations.RemoveField(
            model_name='historicalsupplier',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='nomenclatureitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='nomenclatureitem',
            name='default_supplier',
        ),
        migrations.RemoveField(
            model_name='nomenclatureitem',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='contact_person',
        ),
        migrations.AlterField(
            model_name='contractor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email организации'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон организации'),
        ),
        migrations.AlterField(
            model_name='historicalcontractor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email организации'),
        ),
        migrations.AlterField(
            model_name='historicalcontractor',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон организации'),
        ),
        migrations.AlterField(
            model_name='historicalnomenclatureitem',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='historicalnomenclatureitem',
            name='unit',
            field=models.CharField(default='шт', max_length=50, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='historicalnomenclaturetype',
            name='default_unit',
            field=models.CharField(default='шт', max_length=50, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='historicalsupplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email организации'),
        ),
        migrations.AlterField(
            model_name='historicalsupplier',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон организации'),
        ),
        migrations.AlterField(
            model_name='nomenclatureitem',
            name='code',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='nomenclatureitem',
            name='unit',
            field=models.CharField(default='шт', max_length=50, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='nomenclaturetype',
            name='default_unit',
            field=models.CharField(default='шт', max_length=50, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email организации'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон организации'),
        ),
        migrations.AddField(
            model_name='catalogcategory',
            name='allowed_children',
            field=models.ManyToManyField(blank=True, related_name='allowed_parents', to='persistence.catalogcategory', verbose_name='Допустимые дочерние виды'),
        ),
        migrations.AddField(
            model_name='catalogcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем'),
        ),
        migrations.AddField(
            model_name='catalogcategory',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Удалено пользователем'),
        ),
        migrations.AddField(
            model_name='catalogcategory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновлено пользователем'),
        ),
        migrations.AlterUniqueTogether(
            name='nomenclaturetype',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='historicalnomenclatureitem',
            name='catalog_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='persistence.catalogcategory', verbose_name='Вид справочника'),
        ),
        migrations.AddField(
            model_name='historicalnomenclaturetype',
            name='catalog_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='persistence.catalogcategory', verbose_name='Вид справочника'),
        ),
        migrations.AddField(
            model_name='nomenclatureitem',
            name='catalog_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nomenclature_items', to='persistence.catalogcategory', verbose_name='Вид справочника'),
        ),
        migrations.AddField(
            model_name='nomenclaturetype',
            name='catalog_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nomenclature_types', to='persistence.catalogcategory', verbose_name='Вид справочника'),
        ),
        migrations.AlterUniqueTogether(
            name='nomenclaturetype',
            unique_together={('catalog_category', 'name')},
        ),
        migrations.AddIndex(
            model_name='nomenclatureitem',
            index=models.Index(fields=['catalog_category', 'is_active'], name='nomenclatur_catalog_7d1186_idx'),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='persistence.contractor', verbose_name='Подрядчик'),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем'),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Удалено пользователем'),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='persistence.supplier', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновлено пользователем'),
        ),
        migrations.AddField(
            model_name='historicalcatalogcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем'),
        ),
        migrations.AddField(
            model_name='historicalcatalogcategory',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Удалено пользователем'),
        ),
        migrations.AddField(
            model_name='historicalcatalogcategory',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcatalogcategory',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Обновлено пользователем'),
        ),
        migrations.AddField(
            model_name='historicalcontactperson',
            name='contractor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='persistence.contractor', verbose_name='Подрядчик'),
        ),
        migrations.AddField(
            model_name='historicalcontactperson',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем'),
        ),
        migrations.AddField(
            model_name='historicalcontactperson',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Удалено пользователем'),
        ),
        migrations.AddField(
            model_name='historicalcontactperson',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcontactperson',
            name='supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='persistence.supplier', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='historicalcontactperson',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Обновлено пользователем'),
        ),
        migrations.AddField(
            model_name='historicalnomenclaturesupplier',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем'),
        ),
        migrations.AddField(
            model_name='historicalnomenclaturesupplier',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Удалено пользователем'),
        ),
        migrations.AddField(
            model_name='historicalnomenclaturesupplier',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalnomenclaturesupplier',
            name='nomenclature_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='persistence.nomenclatureitem', verbose_name='Номенклатура'),
        ),
        migrations.AddField(
            model_name='historicalnomenclaturesupplier',
            name='supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='persistence.supplier', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='historicalnomenclaturesupplier',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Обновлено пользователем'),
        ),
        migrations.AddField(
            model_name='nomenclaturesupplier',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем'),
        ),
        migrations.AddField(
            model_name='nomenclaturesupplier',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Удалено пользователем'),
        ),
        migrations.AddField(
            model_name='nomenclaturesupplier',
            name='nomenclature_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_suppliers', to='persistence.nomenclatureitem', verbose_name='Номенклатура'),
        ),
        migrations.AddField(
            model_name='nomenclaturesupplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomenclature_links', to='persistence.supplier', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='nomenclaturesupplier',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновлено пользователем'),
        ),
        migrations.DeleteModel(
            name='HistoricalSupplierOffer',
        ),
        migrations.DeleteModel(
            name='SupplierOffer',
        ),
        migrations.RemoveField(
            model_name='nomenclaturetype',
            name='category',
        ),
        migrations.AlterUniqueTogether(
            name='nomenclaturesupplier',
            unique_together={('nomenclature_item', 'supplier')},
        ),
    ]
