# Generated by Django 5.0.14 on 2026-01-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0005_clear_catalog_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата договора'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='contract_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер договора'),
        ),
        migrations.AddField(
            model_name='historicalcontractor',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата договора'),
        ),
        migrations.AddField(
            model_name='historicalcontractor',
            name='contract_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер договора'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Рейтинг (0-5)'),
        ),
        migrations.AlterField(
            model_name='historicalcontractor',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Рейтинг (0-5)'),
        ),
        migrations.AlterField(
            model_name='historicalsupplier',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Рейтинг (0-5)'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Рейтинг (0-5)'),
        ),
    ]
