# Generated by Django - seed data for delay reasons

from django.db import migrations


def create_delay_reasons(apps, schema_editor):
    """Создание стандартных причин задержек."""
    DelayReason = apps.get_model('persistence', 'DelayReason')
    
    # Причины для закупок
    procurement_reasons = [
        {
            'name': 'Задержка поставщика',
            'description': 'Поставщик не смог выполнить поставку в срок',
            'applies_to_procurement': True,
            'applies_to_production': False,
        },
        {
            'name': 'Нет в наличии у поставщика',
            'description': 'Товар отсутствует на складе поставщика',
            'applies_to_procurement': True,
            'applies_to_production': False,
        },
        {
            'name': 'Задержка оплаты',
            'description': 'Задержка со стороны заказчика по оплате поставщику',
            'applies_to_procurement': True,
            'applies_to_production': False,
        },
        {
            'name': 'Транспортные проблемы',
            'description': 'Проблемы с логистикой и доставкой',
            'applies_to_procurement': True,
            'applies_to_production': False,
        },
        {
            'name': 'Таможенное оформление',
            'description': 'Задержка на таможне при импорте',
            'applies_to_procurement': True,
            'applies_to_production': False,
        },
        {
            'name': 'Брак при приёмке',
            'description': 'Обнаружен брак, требуется замена',
            'applies_to_procurement': True,
            'applies_to_production': False,
        },
        {
            'name': 'Изменение спецификации',
            'description': 'Изменились требования к закупаемой позиции',
            'applies_to_procurement': True,
            'applies_to_production': True,
        },
        {
            'name': 'Смена поставщика',
            'description': 'Требуется найти альтернативного поставщика',
            'applies_to_procurement': True,
            'applies_to_production': False,
        },
    ]
    
    # Причины для производства
    production_reasons = [
        {
            'name': 'Ожидание материалов',
            'description': 'Не поступили необходимые материалы или комплектующие',
            'applies_to_procurement': False,
            'applies_to_production': True,
        },
        {
            'name': 'Ожидание комплектующих',
            'description': 'Не готовы дочерние сборочные единицы',
            'applies_to_procurement': False,
            'applies_to_production': True,
        },
        {
            'name': 'Нехватка персонала',
            'description': 'Недостаточно рабочей силы для выполнения работ',
            'applies_to_procurement': False,
            'applies_to_production': True,
        },
        {
            'name': 'Поломка оборудования',
            'description': 'Выход из строя производственного оборудования',
            'applies_to_procurement': False,
            'applies_to_production': True,
        },
        {
            'name': 'Технологические сложности',
            'description': 'Возникли сложности при изготовлении',
            'applies_to_procurement': False,
            'applies_to_production': True,
        },
        {
            'name': 'Брак при изготовлении',
            'description': 'Обнаружен брак, требуется переделка',
            'applies_to_procurement': False,
            'applies_to_production': True,
        },
        {
            'name': 'Загруженность подрядчика',
            'description': 'Подрядчик не справляется с объёмом работ',
            'applies_to_procurement': False,
            'applies_to_production': True,
        },
        {
            'name': 'Ошибка в КД',
            'description': 'Обнаружена ошибка в конструкторской документации',
            'applies_to_procurement': True,
            'applies_to_production': True,
        },
        {
            'name': 'Несоответствие качества',
            'description': 'Изделие не прошло контроль качества',
            'applies_to_procurement': False,
            'applies_to_production': True,
        },
        {
            'name': 'Изменение приоритетов',
            'description': 'Перепланирование работ по приоритетам',
            'applies_to_procurement': True,
            'applies_to_production': True,
        },
    ]
    
    all_reasons = procurement_reasons + production_reasons
    
    for reason_data in all_reasons:
        DelayReason.objects.get_or_create(
            name=reason_data['name'],
            defaults=reason_data
        )


def remove_delay_reasons(apps, schema_editor):
    """Удаление причин задержек."""
    DelayReason = apps.get_model('persistence', 'DelayReason')
    DelayReason.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0006_add_contractor_contract_fields_and_fix_rating'),
    ]

    operations = [
        migrations.RunPython(create_delay_reasons, remove_delay_reasons),
    ]
