# Generated by Django 5.0.14 on 2026-01-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0007_populate_delay_reasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomitem',
            name='child_category',
            field=models.CharField(blank=True, max_length=50, verbose_name='Категория дочернего элемента (код вида справочника)'),
        ),
        migrations.AlterField(
            model_name='bomstructure',
            name='root_category',
            field=models.CharField(blank=True, max_length=50, verbose_name='Категория корневого изделия (код вида справочника)'),
        ),
        migrations.AlterField(
            model_name='historicalbomitem',
            name='child_category',
            field=models.CharField(blank=True, max_length=50, verbose_name='Категория дочернего элемента (код вида справочника)'),
        ),
        migrations.AlterField(
            model_name='historicalbomstructure',
            name='root_category',
            field=models.CharField(blank=True, max_length=50, verbose_name='Категория корневого изделия (код вида справочника)'),
        ),
        migrations.AddConstraint(
            model_name='bomstructure',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('root_item',), name='unique_active_bom_per_nomenclature'),
        ),
    ]
