# Generated by Django 5.0.14 on 2026-01-17 15:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0010_populate_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprojectitem',
            name='contractor_status',
            field=models.CharField(choices=[('not_started', 'Не начато'), ('sent_to_contractor', 'Передано подрядчику'), ('in_progress', 'В работе у подрядчика'), ('waiting_materials', 'Ожидание материалов у подрядчика'), ('ready_for_pickup', 'Готово к приёмке'), ('quality_check', 'На входном контроле'), ('rework_at_contractor', 'Доработка у подрядчика'), ('completed', 'Принято'), ('rejected', 'Отклонено')], db_index=True, default='not_started', max_length=30, verbose_name='Статус изготовления (подрядчик)'),
        ),
        migrations.AddField(
            model_name='historicalprojectitem',
            name='order_date',
            field=models.DateField(blank=True, help_text='Когда надо оформить закупку (рассчитывается от required_date и срока поставки)', null=True, verbose_name='Дата оформления заказа'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='contractor_status',
            field=models.CharField(choices=[('not_started', 'Не начато'), ('sent_to_contractor', 'Передано подрядчику'), ('in_progress', 'В работе у подрядчика'), ('waiting_materials', 'Ожидание материалов у подрядчика'), ('ready_for_pickup', 'Готово к приёмке'), ('quality_check', 'На входном контроле'), ('rework_at_contractor', 'Доработка у подрядчика'), ('completed', 'Принято'), ('rejected', 'Отклонено')], db_index=True, default='not_started', max_length=30, verbose_name='Статус изготовления (подрядчик)'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='order_date',
            field=models.DateField(blank=True, help_text='Когда надо оформить закупку (рассчитывается от required_date и срока поставки)', null=True, verbose_name='Дата оформления заказа'),
        ),
        migrations.AlterField(
            model_name='historicalproductionprogress',
            name='status',
            field=models.CharField(choices=[('not_started', 'Не начато'), ('in_progress', 'В процессе изготовления'), ('suspended', 'Приостановлено'), ('waiting_materials', 'Ожидание материалов'), ('waiting_components', 'Ожидание комплектующих'), ('quality_check', 'На контроле качества'), ('rework', 'На доработке'), ('completed', 'Изготовлено'), ('rejected', 'Брак')], max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalproductiontask',
            name='status',
            field=models.CharField(choices=[('not_started', 'Не начато'), ('in_progress', 'В процессе изготовления'), ('suspended', 'Приостановлено'), ('waiting_materials', 'Ожидание материалов'), ('waiting_components', 'Ожидание комплектующих'), ('quality_check', 'На контроле качества'), ('rework', 'На доработке'), ('completed', 'Изготовлено'), ('rejected', 'Брак')], db_index=True, default='not_started', max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalprojectitem',
            name='manufacturing_status',
            field=models.CharField(choices=[('not_started', 'Не начато'), ('in_progress', 'В процессе изготовления'), ('suspended', 'Приостановлено'), ('waiting_materials', 'Ожидание материалов'), ('waiting_components', 'Ожидание комплектующих'), ('quality_check', 'На контроле качества'), ('rework', 'На доработке'), ('completed', 'Изготовлено'), ('rejected', 'Брак')], db_index=True, default='not_started', max_length=30, verbose_name='Статус изготовления (свои силы)'),
        ),
        migrations.AlterField(
            model_name='historicalprojectitem',
            name='purchase_status',
            field=models.CharField(choices=[('not_required', 'Не требуется'), ('pending', 'Ожидает заказа'), ('quote_requested', 'Запрошена цена'), ('quote_received', 'Цена получена'), ('ordered', 'Заказано'), ('confirmed', 'Подтверждено поставщиком'), ('in_production', 'В производстве у поставщика'), ('ready_to_ship', 'Готово к отгрузке'), ('in_transit', 'В пути'), ('customs_clearance', 'На таможне'), ('delivered', 'Доставлено'), ('quality_check', 'На входном контроле'), ('accepted', 'Принято на склад'), ('delayed', 'Задержка'), ('partially_delivered', 'Частично доставлено'), ('cancelled', 'Отменено')], db_index=True, default='pending', max_length=30, verbose_name='Статус закупки'),
        ),
        migrations.AlterField(
            model_name='historicalprojectitem',
            name='required_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Требуемая дата поставки'),
        ),
        migrations.AlterField(
            model_name='productionprogress',
            name='status',
            field=models.CharField(choices=[('not_started', 'Не начато'), ('in_progress', 'В процессе изготовления'), ('suspended', 'Приостановлено'), ('waiting_materials', 'Ожидание материалов'), ('waiting_components', 'Ожидание комплектующих'), ('quality_check', 'На контроле качества'), ('rework', 'На доработке'), ('completed', 'Изготовлено'), ('rejected', 'Брак')], max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='productiontask',
            name='status',
            field=models.CharField(choices=[('not_started', 'Не начато'), ('in_progress', 'В процессе изготовления'), ('suspended', 'Приостановлено'), ('waiting_materials', 'Ожидание материалов'), ('waiting_components', 'Ожидание комплектующих'), ('quality_check', 'На контроле качества'), ('rework', 'На доработке'), ('completed', 'Изготовлено'), ('rejected', 'Брак')], db_index=True, default='not_started', max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='manufacturing_status',
            field=models.CharField(choices=[('not_started', 'Не начато'), ('in_progress', 'В процессе изготовления'), ('suspended', 'Приостановлено'), ('waiting_materials', 'Ожидание материалов'), ('waiting_components', 'Ожидание комплектующих'), ('quality_check', 'На контроле качества'), ('rework', 'На доработке'), ('completed', 'Изготовлено'), ('rejected', 'Брак')], db_index=True, default='not_started', max_length=30, verbose_name='Статус изготовления (свои силы)'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='purchase_status',
            field=models.CharField(choices=[('not_required', 'Не требуется'), ('pending', 'Ожидает заказа'), ('quote_requested', 'Запрошена цена'), ('quote_received', 'Цена получена'), ('ordered', 'Заказано'), ('confirmed', 'Подтверждено поставщиком'), ('in_production', 'В производстве у поставщика'), ('ready_to_ship', 'Готово к отгрузке'), ('in_transit', 'В пути'), ('customs_clearance', 'На таможне'), ('delivered', 'Доставлено'), ('quality_check', 'На входном контроле'), ('accepted', 'Принято на склад'), ('delayed', 'Задержка'), ('partially_delivered', 'Частично доставлено'), ('cancelled', 'Отменено')], db_index=True, default='pending', max_length=30, verbose_name='Статус закупки'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='required_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Требуемая дата поставки'),
        ),
        migrations.CreateModel(
            name='SystemModule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Код модуля')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='persistence.systemmodule', verbose_name='Родительский модуль')),
            ],
            options={
                'verbose_name': 'Модуль системы',
                'verbose_name_plural': 'Модули системы',
                'db_table': 'system_modules',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoleModuleAccess',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_level', models.CharField(choices=[('none', 'Нет доступа'), ('view', 'Только просмотр'), ('edit', 'Редактирование'), ('full', 'Полный доступ')], default='view', max_length=20, verbose_name='Уровень доступа')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_access', to='persistence.role', verbose_name='Роль')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_access', to='persistence.systemmodule', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Доступ роли к модулю',
                'verbose_name_plural': 'Доступы ролей к модулям',
                'db_table': 'role_module_access',
                'unique_together': {('role', 'module')},
            },
        ),
        migrations.CreateModel(
            name='UserModuleAccess',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_level', models.CharField(choices=[('none', 'Нет доступа'), ('view', 'Только просмотр'), ('edit', 'Редактирование'), ('full', 'Полный доступ')], default='view', max_length=20, verbose_name='Уровень доступа')),
                ('project_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='ID проекта (если ограничено)')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='persistence.systemmodule', verbose_name='Модуль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_access', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Доступ к модулю',
                'verbose_name_plural': 'Доступы к модулям',
                'db_table': 'user_module_access',
                'unique_together': {('user', 'module', 'project_id')},
            },
        ),
    ]
