# Generated by Django 5.0.14 on 2026-01-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0011_historicalprojectitem_contractor_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprojectitem',
            name='purchase_by_contractor',
            field=models.BooleanField(default=False, verbose_name='Закупается подрядчиком'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='purchase_by_contractor',
            field=models.BooleanField(default=False, verbose_name='Закупается подрядчиком'),
        ),
    ]