# Generated by Django 5.0.14 on 2026-01-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0012_projectitem_purchase_by_contractor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproductionprogress',
            name='status',
            field=models.CharField(choices=[('not_started', 'Не начато'), ('in_progress', 'В процессе изготовления'), ('suspended', 'Приостановлено'), ('waiting_materials', 'Ожидание материалов и/или комплектующих'), ('quality_check', 'На контроле качества'), ('rework', 'На доработке'), ('completed', 'Изготовлено'), ('rejected', 'Брак')], max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalproductiontask',
            name='material_supply_type',
            field=models.CharField(choices=[('our_supply', 'Материалы и комплектующие закупаем мы'), ('contractor_supply', 'Материалы и комплектующие закупает подрядчик')], default='our_supply', max_length=30, verbose_name='Снабжение материалами'),
        ),
        migrations.AlterField(
            model_name='historicalproductiontask',
            name='status',
            field=models.CharField(choices=[('not_started', 'Не начато'), ('in_progress', 'В процессе изготовления'), ('suspended', 'Приостановлено'), ('waiting_materials', 'Ожидание материалов и/или комплектующих'), ('quality_check', 'На контроле качества'), ('rework', 'На доработке'), ('completed', 'Изготовлено'), ('rejected', 'Брак')], db_index=True, default='not_started', max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalprojectitem',
            name='manufacturing_status',
            field=models.CharField(choices=[('not_started', 'Не начато'), ('in_progress', 'В процессе изготовления'), ('suspended', 'Приостановлено'), ('waiting_materials', 'Ожидание материалов и/или комплектующих'), ('quality_check', 'На контроле качества'), ('rework', 'На доработке'), ('completed', 'Изготовлено'), ('rejected', 'Брак')], db_index=True, default='not_started', max_length=30, verbose_name='Статус изготовления (свои силы)'),
        ),
        migrations.AlterField(
            model_name='historicalprojectitem',
            name='material_supply_type',
            field=models.CharField(choices=[('our_supply', 'Материалы и комплектующие закупаем мы'), ('contractor_supply', 'Материалы и комплектующие закупает подрядчик')], default='our_supply', max_length=30, verbose_name='Снабжение материалами'),
        ),
        migrations.AlterField(
            model_name='productionprogress',
            name='status',
            field=models.CharField(choices=[('not_started', 'Не начато'), ('in_progress', 'В процессе изготовления'), ('suspended', 'Приостановлено'), ('waiting_materials', 'Ожидание материалов и/или комплектующих'), ('quality_check', 'На контроле качества'), ('rework', 'На доработке'), ('completed', 'Изготовлено'), ('rejected', 'Брак')], max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='productiontask',
            name='material_supply_type',
            field=models.CharField(choices=[('our_supply', 'Материалы и комплектующие закупаем мы'), ('contractor_supply', 'Материалы и комплектующие закупает подрядчик')], default='our_supply', max_length=30, verbose_name='Снабжение материалами'),
        ),
        migrations.AlterField(
            model_name='productiontask',
            name='status',
            field=models.CharField(choices=[('not_started', 'Не начато'), ('in_progress', 'В процессе изготовления'), ('suspended', 'Приостановлено'), ('waiting_materials', 'Ожидание материалов и/или комплектующих'), ('quality_check', 'На контроле качества'), ('rework', 'На доработке'), ('completed', 'Изготовлено'), ('rejected', 'Брак')], db_index=True, default='not_started', max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='manufacturing_status',
            field=models.CharField(choices=[('not_started', 'Не начато'), ('in_progress', 'В процессе изготовления'), ('suspended', 'Приостановлено'), ('waiting_materials', 'Ожидание материалов и/или комплектующих'), ('quality_check', 'На контроле качества'), ('rework', 'На доработке'), ('completed', 'Изготовлено'), ('rejected', 'Брак')], db_index=True, default='not_started', max_length=30, verbose_name='Статус изготовления (свои силы)'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='material_supply_type',
            field=models.CharField(choices=[('our_supply', 'Материалы и комплектующие закупаем мы'), ('contractor_supply', 'Материалы и комплектующие закупает подрядчик')], default='our_supply', max_length=30, verbose_name='Снабжение материалами'),
        ),
    ]
