# Generated by Django 5.0.14 on 2026-01-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0015_add_stock_transfer_material_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='delayreason',
            name='production_config',
            field=models.CharField(choices=[('all', 'Все конфигурации'), ('internal', 'Своими силами'), ('contractor_our_supply', 'Подрядчик (мы снабжаем)'), ('contractor_their_supply', 'Подрядчик (сам закупает)')], default='all', help_text='Указывает для каких конфигураций производства применима эта причина', max_length=30, verbose_name='Конфигурация производства'),
        ),
        migrations.AddField(
            model_name='historicaldelayreason',
            name='production_config',
            field=models.CharField(choices=[('all', 'Все конфигурации'), ('internal', 'Своими силами'), ('contractor_our_supply', 'Подрядчик (мы снабжаем)'), ('contractor_their_supply', 'Подрядчик (сам закупает)')], default='all', help_text='Указывает для каких конфигураций производства применима эта причина', max_length=30, verbose_name='Конфигурация производства'),
        ),
    ]
