# Generated by Django 5.0.14 on 2026-01-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0016_delayreason_production_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='visibility_type',
            field=models.CharField(choices=[('own', 'Видит только свои позиции'), ('own_and_children', 'Видит свои и дочерние позиции'), ('all', 'Видит все позиции')], default='all', help_text='Определяет какие позиции проекта видит пользователь с этой ролью', max_length=20, verbose_name='Права видимости объектов'),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_be_inventory_responsible',
            field=models.BooleanField(default=False, help_text='Пользователь отображается в списке ответственных для инвентаризации склада', verbose_name='Может быть ответственным по инвентаризации'),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_be_production_responsible',
            field=models.BooleanField(default=False, help_text='Пользователи с этой ролью отображаются в списке ответственных при назначении на позиции проекта', verbose_name='Может быть ответственным по производству'),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_be_responsible',
            field=models.BooleanField(default=False, help_text='Устаревшее поле - используйте can_be_production_responsible', verbose_name='Может быть ответственным (устар.)'),
        ),
        migrations.AlterField(
            model_name='role',
            name='see_child_structures',
            field=models.BooleanField(default=False, help_text='Устаревшее поле - используйте visibility_type', verbose_name='Видит дочерние структуры (устар.)'),
        ),
        migrations.AlterField(
            model_name='role',
            name='see_only_own_items',
            field=models.BooleanField(default=False, help_text='Устаревшее поле - используйте visibility_type', verbose_name='Видит только свои позиции (устар.)'),
        ),
    ]
