# Generated by Django 5.0.14 on 2026-01-18 21:29

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0017_role_visibility_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmaterialrequirement',
            name='bom_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='persistence.bomitem', verbose_name='Позиция BOM'),
        ),
        migrations.AddField(
            model_name='historicalmaterialrequirement',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='persistence.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='historicalmaterialrequirement',
            name='project_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='persistence.projectitem', verbose_name='Позиция проекта (система/подсистема/работа)'),
        ),
        migrations.AddField(
            model_name='materialrequirement',
            name='bom_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_requirements', to='persistence.bomitem', verbose_name='Позиция BOM'),
        ),
        migrations.AddField(
            model_name='materialrequirement',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_requirements', to='persistence.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='materialrequirement',
            name='project_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_requirements', to='persistence.projectitem', verbose_name='Позиция проекта (система/подсистема/работа)'),
        ),
        migrations.AlterField(
            model_name='historicalmaterialrequirement',
            name='status',
            field=models.CharField(choices=[('waiting_purchase', 'Ожидает закупки'), ('in_order', 'В заказе'), ('partial_received', 'Частично получено'), ('closed', 'Закрыта'), ('calculated', 'Рассчитано'), ('in_procurement', 'В закупке'), ('ordered', 'Заказано'), ('fulfilled', 'Выполнено')], default='calculated', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('ordered', 'Заказан'), ('partially_delivered', 'Частично поставлен'), ('closed', 'Закрыт'), ('cancelled', 'Отменён')], db_index=True, default='draft', max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='materialrequirement',
            name='status',
            field=models.CharField(choices=[('waiting_purchase', 'Ожидает закупки'), ('in_order', 'В заказе'), ('partial_received', 'Частично получено'), ('closed', 'Закрыта'), ('calculated', 'Рассчитано'), ('in_procurement', 'В закупке'), ('ordered', 'Заказано'), ('fulfilled', 'Выполнено')], default='calculated', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('ordered', 'Заказан'), ('partially_delivered', 'Частично поставлен'), ('closed', 'Закрыт'), ('cancelled', 'Отменён')], db_index=True, default='draft', max_length=30, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Номер документа')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено')], default='draft', max_length=20, verbose_name='Статус')),
                ('receipt_date', models.DateField(verbose_name='Дата поступления')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Удалено пользователем')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='persistence.purchaseorder', verbose_name='Заказ на закупку')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts', to=settings.AUTH_USER_MODEL, verbose_name='Принял')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновлено пользователем')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='persistence.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Поступление',
                'verbose_name_plural': 'Поступления',
                'db_table': 'goods_receipts',
                'ordering': ['-receipt_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Количество')),
                ('batch_number', models.CharField(blank=True, max_length=50, verbose_name='Номер партии')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Удалено пользователем')),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='persistence.goodsreceipt', verbose_name='Поступление')),
                ('purchase_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_items', to='persistence.purchaseorderitem', verbose_name='Позиция заказа')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновлено пользователем')),
            ],
            options={
                'verbose_name': 'Позиция поступления',
                'verbose_name_plural': 'Позиции поступлений',
                'db_table': 'goods_receipt_items',
            },
        ),
        migrations.CreateModel(
            name='HistoricalGoodsReceipt',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('number', models.CharField(db_index=True, max_length=50, verbose_name='Номер документа')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено')], default='draft', max_length=20, verbose_name='Статус')),
                ('receipt_date', models.DateField(verbose_name='Дата поступления')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Удалено пользователем')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='persistence.purchaseorder', verbose_name='Заказ на закупку')),
                ('received_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Принял')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Обновлено пользователем')),
                ('warehouse', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='persistence.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'historical Поступление',
                'verbose_name_plural': 'historical Поступления',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalGoodsReceiptItem',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Количество')),
                ('batch_number', models.CharField(blank=True, max_length=50, verbose_name='Номер партии')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Удалено пользователем')),
                ('goods_receipt', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='persistence.goodsreceipt', verbose_name='Поступление')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('purchase_order_item', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='persistence.purchaseorderitem', verbose_name='Позиция заказа')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Обновлено пользователем')),
            ],
            options={
                'verbose_name': 'historical Позиция поступления',
                'verbose_name_plural': 'historical Позиции поступлений',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
