# Generated by Django 5.0.14 on 2026-01-19 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0019_erp_requirements_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprojectitem',
            name='has_problem',
            field=models.BooleanField(db_index=True, default=False, help_text='Флаг наличия проблемы (задержка, брак, срыв сроков и т.д.)', verbose_name='Есть проблема'),
        ),
        migrations.AddField(
            model_name='historicalprojectitem',
            name='problem_notes',
            field=models.TextField(blank=True, verbose_name='Комментарий к проблеме'),
        ),
        migrations.AddField(
            model_name='historicalprojectitem',
            name='problem_reason',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Причина из справочника причин проблем', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='persistence.problemreason', verbose_name='Причина проблемы'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='has_problem',
            field=models.BooleanField(db_index=True, default=False, help_text='Флаг наличия проблемы (задержка, брак, срыв сроков и т.д.)', verbose_name='Есть проблема'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='problem_notes',
            field=models.TextField(blank=True, verbose_name='Комментарий к проблеме'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='problem_reason',
            field=models.ForeignKey(blank=True, help_text='Причина из справочника причин проблем', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_items', to='persistence.problemreason', verbose_name='Причина проблемы'),
        ),
        migrations.AlterField(
            model_name='historicalprojectitem',
            name='purchase_status',
            field=models.CharField(choices=[('not_required', 'Не требуется'), ('waiting_order', 'Ожидает заказа'), ('in_order', 'В заказе'), ('closed', 'Закрыта'), ('pending', 'Ожидает заказа (legacy)'), ('quote_requested', 'Запрошена цена (legacy)'), ('quote_received', 'Цена получена (legacy)'), ('ordered', 'Заказано (legacy)'), ('confirmed', 'Подтверждено (legacy)'), ('in_production', 'В производстве (legacy)'), ('ready_to_ship', 'Готово к отгрузке (legacy)'), ('in_transit', 'В пути (legacy)'), ('customs_clearance', 'На таможне (legacy)'), ('delivered', 'Доставлено (legacy)'), ('quality_check', 'На входном контроле (legacy)'), ('accepted', 'Принято на склад (legacy)'), ('delayed', 'Задержка (legacy)'), ('partially_delivered', 'Частично доставлено (legacy)'), ('cancelled', 'Отменено (legacy)')], db_index=True, default='pending', max_length=30, verbose_name='Статус закупки'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='purchase_status',
            field=models.CharField(choices=[('not_required', 'Не требуется'), ('waiting_order', 'Ожидает заказа'), ('in_order', 'В заказе'), ('closed', 'Закрыта'), ('pending', 'Ожидает заказа (legacy)'), ('quote_requested', 'Запрошена цена (legacy)'), ('quote_received', 'Цена получена (legacy)'), ('ordered', 'Заказано (legacy)'), ('confirmed', 'Подтверждено (legacy)'), ('in_production', 'В производстве (legacy)'), ('ready_to_ship', 'Готово к отгрузке (legacy)'), ('in_transit', 'В пути (legacy)'), ('customs_clearance', 'На таможне (legacy)'), ('delivered', 'Доставлено (legacy)'), ('quality_check', 'На входном контроле (legacy)'), ('accepted', 'Принято на склад (legacy)'), ('delayed', 'Задержка (legacy)'), ('partially_delivered', 'Частично доставлено (legacy)'), ('cancelled', 'Отменено (legacy)')], db_index=True, default='pending', max_length=30, verbose_name='Статус закупки'),
        ),
    ]
