# Generated by GitHub Copilot

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0023_rename_closed_status_to_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprojectitem',
            name='item_number',
            field=models.PositiveBigIntegerField(
                blank=True,
                null=True,
                db_index=True,
                verbose_name='ID позиции',
            ),
        ),
    ]
