# Generated by GitHub Copilot

from django.db import migrations
from django.db.models import Max


def sync_project_item_sequence(apps, schema_editor):
    ProjectItem = apps.get_model('persistence', 'ProjectItem')
    ProjectItemSequence = apps.get_model('persistence', 'ProjectItemSequence')

    max_item_number = ProjectItem.objects.aggregate(m=Max('item_number')).get('m') or 0

    seq, _ = ProjectItemSequence.objects.update_or_create(
        key='project_item',
        defaults={'last_value': max_item_number},
    )

    # If multiple migrations/seeds touched the counter, keep the larger value
    if seq.last_value < max_item_number:
        seq.last_value = max_item_number
        seq.save(update_fields=['last_value'])


def rollback_sync_project_item_sequence(apps, schema_editor):
    # No safe rollback for counter synchronization.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0024_add_item_number_to_historicalprojectitem'),
    ]

    operations = [
        migrations.RunPython(sync_project_item_sequence, rollback_sync_project_item_sequence),
    ]
