# Generated by Django 5.0.14 on 2026-01-28 17:14

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0027_fill_missing_project_item_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproject',
            name='code',
        ),
        migrations.AddField(
            model_name='historicalprojectitem',
            name='manufacturing_problem_reason',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='persistence.manufacturingproblemreason', verbose_name='Причина (аналитика, производство)'),
        ),
        migrations.AddField(
            model_name='historicalprojectitem',
            name='purchase_problem_reason',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='persistence.purchaseproblemreason', verbose_name='Причина (аналитика, закупки)'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='manufacturing_problem_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_items', to='persistence.manufacturingproblemreason', verbose_name='Причина (аналитика, производство)'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='purchase_problem_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_items', to='persistence.purchaseproblemreason', verbose_name='Причина (аналитика, закупки)'),
        ),
        migrations.AlterField(
            model_name='historicalmaterialrequirement',
            name='status',
            field=models.CharField(choices=[('waiting_order', 'Ожидает заказа'), ('in_order', 'В заказе'), ('closed', 'На складе'), ('written_off', 'Списано')], db_index=True, default='waiting_order', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalproductionprogress',
            name='status',
            field=models.CharField(choices=[('not_started', 'Не начато'), ('in_progress', 'В работе'), ('suspended', 'Приостановлено'), ('completed', 'Изготовлено')], max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalproductiontask',
            name='status',
            field=models.CharField(choices=[('not_started', 'Не начато'), ('in_progress', 'В работе'), ('suspended', 'Приостановлено'), ('completed', 'Изготовлено')], db_index=True, default='not_started', max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalprojectitem',
            name='contractor_status',
            field=models.CharField(blank=True, choices=[('sent_to_contractor', 'Передано подрядчику'), ('in_progress_by_contractor', 'В работе подрядчиком'), ('suspended_by_contractor', 'Приостановлено подрядчиком'), ('manufactured_by_contractor', 'Изготовлено подрядчиком'), ('completed', 'Изготовлено')], db_index=True, default='sent_to_contractor', max_length=30, verbose_name='Статус изготовления (подрядчик)'),
        ),
        migrations.AlterField(
            model_name='historicalprojectitem',
            name='manufacturing_status',
            field=models.CharField(choices=[('not_started', 'Не начато'), ('in_progress', 'В работе'), ('suspended', 'Приостановлено'), ('completed', 'Изготовлено')], db_index=True, default='not_started', max_length=30, verbose_name='Статус изготовления (свои силы)'),
        ),
        migrations.AlterField(
            model_name='historicalprojectitem',
            name='purchase_status',
            field=models.CharField(choices=[('waiting_order', 'Ожидает заказа'), ('in_order', 'В заказе'), ('closed', 'На складе'), ('written_off', 'Списано')], db_index=True, default='waiting_order', max_length=30, verbose_name='Статус закупки'),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('ordered', 'Заказан'), ('partially_delivered', 'Частично поставлен'), ('closed', 'Закрыт'), ('cancelled', 'Отменен')], db_index=True, default='draft', max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalstockmovement',
            name='movement_type',
            field=models.CharField(choices=[('receipt', 'Приход'), ('issue', 'Расход'), ('transfer_out', 'Перемещение (отправка)'), ('transfer_in', 'Перемещение (приём)'), ('transfer', 'Перемещение'), ('adjustment', 'Корректировка'), ('return', 'Возврат'), ('inventory', 'Инвентаризация'), ('contractor_writeoff', 'Списание подрядчику'), ('contractor_receipt', 'Приёмка от подрядчика'), ('production', 'Производство'), ('consumption', 'Потребление')], max_length=20, verbose_name='Тип движения'),
        ),
        migrations.AlterField(
            model_name='historicalstockmovement',
            name='source_document',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Документ-основание'),
        ),
        migrations.AlterField(
            model_name='materialrequirement',
            name='status',
            field=models.CharField(choices=[('waiting_order', 'Ожидает заказа'), ('in_order', 'В заказе'), ('closed', 'На складе'), ('written_off', 'Списано')], db_index=True, default='waiting_order', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='productionprogress',
            name='status',
            field=models.CharField(choices=[('not_started', 'Не начато'), ('in_progress', 'В работе'), ('suspended', 'Приостановлено'), ('completed', 'Изготовлено')], max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='productiontask',
            name='status',
            field=models.CharField(choices=[('not_started', 'Не начато'), ('in_progress', 'В работе'), ('suspended', 'Приостановлено'), ('completed', 'Изготовлено')], db_index=True, default='not_started', max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='contractor_status',
            field=models.CharField(blank=True, choices=[('sent_to_contractor', 'Передано подрядчику'), ('in_progress_by_contractor', 'В работе подрядчиком'), ('suspended_by_contractor', 'Приостановлено подрядчиком'), ('manufactured_by_contractor', 'Изготовлено подрядчиком'), ('completed', 'Изготовлено')], db_index=True, default='sent_to_contractor', max_length=30, verbose_name='Статус изготовления (подрядчик)'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='manufacturing_status',
            field=models.CharField(choices=[('not_started', 'Не начато'), ('in_progress', 'В работе'), ('suspended', 'Приостановлено'), ('completed', 'Изготовлено')], db_index=True, default='not_started', max_length=30, verbose_name='Статус изготовления (свои силы)'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='purchase_status',
            field=models.CharField(choices=[('waiting_order', 'Ожидает заказа'), ('in_order', 'В заказе'), ('closed', 'На складе'), ('written_off', 'Списано')], db_index=True, default='waiting_order', max_length=30, verbose_name='Статус закупки'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('ordered', 'Заказан'), ('partially_delivered', 'Частично поставлен'), ('closed', 'Закрыт'), ('cancelled', 'Отменен')], db_index=True, default='draft', max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('receipt', 'Приход'), ('issue', 'Расход'), ('transfer_out', 'Перемещение (отправка)'), ('transfer_in', 'Перемещение (приём)'), ('transfer', 'Перемещение'), ('adjustment', 'Корректировка'), ('return', 'Возврат'), ('inventory', 'Инвентаризация'), ('contractor_writeoff', 'Списание подрядчику'), ('contractor_receipt', 'Приёмка от подрядчика'), ('production', 'Производство'), ('consumption', 'Потребление')], max_length=20, verbose_name='Тип движения'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='source_document',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Документ-основание'),
        ),
        migrations.CreateModel(
            name='HistoricalManufacturingProblemSubreason',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Удалено пользователем')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reason', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='persistence.manufacturingproblemreason', verbose_name='Причина (изготовление)')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Обновлено пользователем')),
            ],
            options={
                'verbose_name': 'historical Подпричина проблемы изготовления',
                'verbose_name_plural': 'historical Подпричины проблем изготовления',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPurchaseProblemSubreason',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Удалено пользователем')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reason', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='persistence.purchaseproblemreason', verbose_name='Причина (закупка)')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Обновлено пользователем')),
            ],
            options={
                'verbose_name': 'historical Подпричина проблемы закупки',
                'verbose_name_plural': 'historical Подпричины проблем закупок',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ManufacturingProblemSubreason',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Удалено пользователем')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subreasons', to='persistence.manufacturingproblemreason', verbose_name='Причина (изготовление)')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновлено пользователем')),
            ],
            options={
                'verbose_name': 'Подпричина проблемы изготовления',
                'verbose_name_plural': 'Подпричины проблем изготовления',
                'db_table': 'manufacturing_problem_subreasons',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='historicalprojectitem',
            name='manufacturing_problem_subreason',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='persistence.manufacturingproblemsubreason', verbose_name='Подпричина (аналитика, производство)'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='manufacturing_problem_subreason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_items', to='persistence.manufacturingproblemsubreason', verbose_name='Подпричина (аналитика, производство)'),
        ),
        migrations.CreateModel(
            name='PurchaseProblemSubreason',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Удалено пользователем')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subreasons', to='persistence.purchaseproblemreason', verbose_name='Причина (закупка)')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновлено пользователем')),
            ],
            options={
                'verbose_name': 'Подпричина проблемы закупки',
                'verbose_name_plural': 'Подпричины проблем закупок',
                'db_table': 'purchase_problem_subreasons',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='historicalprojectitem',
            name='purchase_problem_subreason',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='persistence.purchaseproblemsubreason', verbose_name='Подпричина (аналитика, закупки)'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='purchase_problem_subreason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_items', to='persistence.purchaseproblemsubreason', verbose_name='Подпричина (аналитика, закупки)'),
        ),
        migrations.AddConstraint(
            model_name='manufacturingproblemsubreason',
            constraint=models.UniqueConstraint(fields=('reason', 'name'), name='uq_manufacturing_subreason_reason_name'),
        ),
        migrations.AddConstraint(
            model_name='purchaseproblemsubreason',
            constraint=models.UniqueConstraint(fields=('reason', 'name'), name='uq_purchase_subreason_reason_name'),
        ),
    ]
