# Generated by Django - seed data for manufacturing/purchase problem reasons with subreasons

from django.db import migrations


def _slug(code: str) -> str:
    return code.strip().lower().replace(' ', '_').replace('/', '_').replace('-', '_')


MANUFACTURING_DATA = [
    (
        {
            'code': 'm_supply',
            'name': 'Снабжение',
            'severity': 2,
            'sort_order': 10,
            'description': '',
            'suggested_action': '',
            'is_active': True,
        },
        [
            'задержка поставки материалов',
            'отсутствие материала',
            'ошибка спецификации',
            'замена материала / аналога',
            'несоответствие качества',
            'зависимость от другой позиции',
        ],
    ),
    (
        {
            'code': 'm_technology_kd',
            'name': 'Технология / КД',
            'severity': 2,
            'sort_order': 20,
            'description': '',
            'suggested_action': '',
            'is_active': True,
        },
        [
            'ошибка в КД',
            'доработка после старта',
            'изменение требований',
            'несогласованное изменение',
            'технологическая невозможность',
            'нет утверждённой версии КД',
        ],
    ),
    (
        {
            'code': 'm_planning_timing',
            'name': 'Планирование / Сроки',
            'severity': 2,
            'sort_order': 30,
            'description': '',
            'suggested_action': '',
            'is_active': True,
        },
        [
            'неверная оценка сроков',
            'зависимость от других этапов',
            'сдвиг предыдущих работ',
            'конфликт ресурсов',
            'перепланирование проекта',
        ],
    ),
    (
        {
            'code': 'm_resources',
            'name': 'Ресурсы (кадры / мощности)',
            'severity': 2,
            'sort_order': 40,
            'description': '',
            'suggested_action': '',
            'is_active': True,
        },
        [
            'нехватка персонала',
            'перегруз исполнителей',
            'недостаточная квалификация',
            'поломка оборудования',
            'замена исполнителя',
        ],
    ),
    (
        {
            'code': 'm_contractor',
            'name': 'Подрядчик',
            'severity': 2,
            'sort_order': 50,
            'description': '',
            'suggested_action': '',
            'is_active': True,
        },
        [
            'срыв сроков',
            'проблемы с качеством',
            'приостановка работ подрядчиком',
            'несогласованность коммуникации',
            'ожидание материалов от нас',
            'нарушение договорённостей',
        ],
    ),
]

PURCHASE_DATA = [
    (
        {
            'code': 'p_financing',
            'name': 'Финансирование',
            'severity': 2,
            'sort_order': 10,
            'description': '',
            'suggested_action': '',
            'is_active': True,
        },
        [
            'не утверждён бюджет',
            'превышен лимит',
            'кассовый разрыв',
            'ожидание финансирования',
        ],
    ),
    (
        {
            'code': 'p_supplier_availability',
            'name': 'Наличие у поставщиков',
            'severity': 2,
            'sort_order': 20,
            'description': '',
            'suggested_action': '',
            'is_active': True,
        },
        [
            'нет в наличии',
            'снято с производства',
            'дефицит на рынке',
            'долгий срок изготовления',
        ],
    ),
    (
        {
            'code': 'p_supplier_logistics',
            'name': 'Поставщик / Логистика',
            'severity': 2,
            'sort_order': 30,
            'description': '',
            'suggested_action': '',
            'is_active': True,
        },
        [
            'задержка поставки',
            'срыв срока поставщиком',
            'логистическая задержка',
            'таможня',
            'транспортная проблема',
        ],
    ),
    (
        {
            'code': 'p_approvals_procedures',
            'name': 'Согласование / Процедуры',
            'severity': 2,
            'sort_order': 40,
            'description': '',
            'suggested_action': '',
            'is_active': True,
        },
        [
            'ожидание договора',
            'согласование ТЗ',
            'согласование условий',
            'внутренняя бюрократия',
        ],
    ),
    (
        {
            'code': 'p_quality_compliance',
            'name': 'Качество / Соответствие',
            'severity': 2,
            'sort_order': 50,
            'description': '',
            'suggested_action': '',
            'is_active': True,
        },
        [
            'несоответствие спецификации',
            'брак',
            'ошибка комплектации',
            'возврат / рекламация',
        ],
    ),
]


def populate_problem_reasons(apps, schema_editor):
    ManufacturingProblemReason = apps.get_model('persistence', 'ManufacturingProblemReason')
    PurchaseProblemReason = apps.get_model('persistence', 'PurchaseProblemReason')
    ManufacturingProblemSubreason = apps.get_model('persistence', 'ManufacturingProblemSubreason')
    PurchaseProblemSubreason = apps.get_model('persistence', 'PurchaseProblemSubreason')

    # Clear old reference data (requested: remove old and insert new)
    ManufacturingProblemSubreason.objects.all().delete()
    PurchaseProblemSubreason.objects.all().delete()
    ManufacturingProblemReason.objects.all().delete()
    PurchaseProblemReason.objects.all().delete()

    for reason_data, subreasons in MANUFACTURING_DATA:
        reason = ManufacturingProblemReason.objects.create(**reason_data)
        for idx, name in enumerate(subreasons, start=1):
            ManufacturingProblemSubreason.objects.create(
                reason=reason,
                name=name,
                sort_order=idx * 10,
                is_active=True,
            )

    for reason_data, subreasons in PURCHASE_DATA:
        reason = PurchaseProblemReason.objects.create(**reason_data)
        for idx, name in enumerate(subreasons, start=1):
            PurchaseProblemSubreason.objects.create(
                reason=reason,
                name=name,
                sort_order=idx * 10,
                is_active=True,
            )


def rollback_problem_reasons(apps, schema_editor):
    ManufacturingProblemReason = apps.get_model('persistence', 'ManufacturingProblemReason')
    PurchaseProblemReason = apps.get_model('persistence', 'PurchaseProblemReason')
    ManufacturingProblemSubreason = apps.get_model('persistence', 'ManufacturingProblemSubreason')
    PurchaseProblemSubreason = apps.get_model('persistence', 'PurchaseProblemSubreason')

    ManufacturingProblemSubreason.objects.all().delete()
    PurchaseProblemSubreason.objects.all().delete()
    ManufacturingProblemReason.objects.filter(code__startswith='m_').delete()
    PurchaseProblemReason.objects.filter(code__startswith='p_').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0028_remove_historicalproject_code_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_problem_reasons, rollback_problem_reasons),
    ]
