# Generated by Django 5.0.14 on 2026-01-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0029_populate_problem_reasons_subreasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='child_structure_access',
            field=models.CharField(choices=[('name_only', 'Только наименование'), ('view', 'Просмотр'), ('edit', 'Редактирование')], default='name_only', help_text='Определяет уровень доступа к дочерним структурам, где назначен другой ответственный', max_length=20, verbose_name='Доступ к дочерним структурам с другим ответственным'),
        ),
    ]
