# Generated by Django 5.0.14 on 2026-01-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0030_add_child_structure_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='project_access_scope',
            field=models.CharField(choices=[('own', 'Только свои позиции'), ('own_children_name_only', 'Свои позиции + дочерние (только наименования)'), ('own_children_view', 'Свои позиции + дочерние (просмотр)'), ('own_children_edit', 'Свои позиции + дочерние (редактирование)'), ('all', 'Все проекты (полный доступ)')], default='all', help_text='Определяет видимость и доступ к проектам и позициям в иерархии', max_length=30, verbose_name='Область видимости и доступ'),
        ),
        migrations.AlterField(
            model_name='role',
            name='child_structure_access',
            field=models.CharField(choices=[('name_only', 'Только наименование'), ('view', 'Просмотр'), ('edit', 'Редактирование')], default='name_only', help_text='Устаревшее поле - используйте project_access_scope', max_length=20, verbose_name='Доступ к дочерним структурам (устар.)'),
        ),
        migrations.AlterField(
            model_name='role',
            name='visibility_type',
            field=models.CharField(choices=[('own', 'Видит только свои позиции'), ('own_and_children', 'Видит свои и дочерние позиции'), ('all', 'Видит все позиции')], default='all', help_text='Устаревшее поле - используйте project_access_scope', max_length=20, verbose_name='Права видимости объектов (устар.)'),
        ),
    ]
